name: release-publish

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Tipo de actualización de versión (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Bump version, Create PR and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # 1. Crear una nueva rama temporal
          BRANCH_NAME="release/bump-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME

          # 2. Subir la versión (crea el commit y el tag localmente)
          npm version ${{ github.event.inputs.version_bump }} -m "chore(release): %s"

          # 3. Subir la rama y el tag a GitHub
          git push origin $BRANCH_NAME
          git push origin --tags

          # 4. Crear el Pull Request usando GitHub CLI
          gh pr create \
            --title "chore(release): Actualización de versión" \
            --body "PR generado automáticamente por GitHub Actions para subir la versión." \
            --base master \
            --head $BRANCH_NAME

          # 5. Publicar a NPM
          npm publish
